# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hjwdPOLA0PyGogB9lAzDgVMNAXTSeNWb
"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Data
data = np.random.randn(1000)
categories = ['A', 'B', 'C', 'D']
values = [15, 30, 45, 10]
x = np.linspace(0, 10, 50)
y = np.sin(x)
scatter_x, scatter_y = np.random.rand(50) * 10, np.random.rand(50) * 10
heatmap_data = np.random.rand(5, 5)

# Plots
plt.hist(data, bins=30); plt.title("Histogram"); plt.show()
plt.bar(categories, values); plt.title("Bar Diagram"); plt.show()
plt.pie(values, labels=categories, autopct='%1.1f%%'); plt.title("Pie Chart"); plt.show()
plt.plot(x, y); plt.title("Line Plot"); plt.show()
plt.scatter(scatter_x, scatter_y); plt.title("Scatter Plot"); plt.show()
plt.boxplot(data); plt.title("Box Plot"); plt.show()
sns.heatmap(heatmap_data, annot=True, cmap='coolwarm'); plt.title("Heat Map"); plt.show()